test: &default
  mode: sandbox
  client_id: <%= ENV.fetch('client_id') %>
  client_secret: <%= ENV.fetch('client_secret') %>

development:
  <<: *default

production:
  mode: live
  client_id: CLIENT_ID
  client_secret: CLIENT_SECRET
  # rest_endpoint: "https://api.paypal.com"
